
name: Release_Build_master-new_windows_sdk

on:
  workflow_dispatch:
  #watch:
  #  types: started
  repository_dispatch:
    types: relase_build
    
jobs:
  iot2000-image:
    name:  image build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Free Disk Space
        uses: ./.github/workflows/free-disk-space
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Build image
        run: |
          echo "GITHUB_PATH: ${{github.GITHUB_PATH}}" \
          && echo "GITHUB_ACTION_PATH ${{github.GITHUB_ACTION_PATH}}" \
          && git reset --hard && git fetch && git checkout master && git pull origin master \
          && wget https://raw.githubusercontent.com/siemens/kas/2.6.2/kas-container &&  chmod a+x kas-container \
          && ./kas-container build kas-sdk-windows-i586.yml 
      - name: Archive windows sdk
        uses: actions/upload-artifact@v2
        with:
          name: iot2000-windows-SDK
          path: build/tmp/deploy/sdk/poky-iot2000-glibc-i686-mingw32-iot2000-example-image-i586-*.tar.xz
